server:
  port: 8080
spring:
  application:
    name: "auth"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3300/authdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://configserver-ms:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

